// app/router.tsx
import { createRouter as createTanStackRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen' // generated by start script

/**
 * # What is this file?
 * 
 * This is the file that will dictate the behavior of TanStack Router used 
 * within Start. In this file, you can configure everything from the default 
 * preloading functionality to caching staleness.
 * 
 * https://tanstack.com/start/latest/docs/framework/react/build-from-scratch#the-router-configuration
 */

export function createRouter() {
  const router = createTanStackRouter({
    routeTree,
    // Notice this scrollRestoration property. This is used to restore the scroll position of the page when navigating between routes.
    scrollRestoration: true,
  })

  return router
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof createRouter>
  }
}